on: [pull_request]

jobs:
  test:
    name: PHP lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        uses: ./.github/actions/php-test
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: global-composer-files-cache-${{ hashFiles('composer.json') }}
          # key: global-composer-files-cache-${{ hashFiles('composer.lock') }} # if composer.lock is exists
      - name: Install dependencies
        run: "composer install --prefer-dist --no-progress --no-suggest"
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: Check CS
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: composer cs -- -n --report=emacs | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m'
      - name: Check Stan
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: composer stan -- --error-format=raw | reviewdog -reporter=github-pr-review -f=phpstan
